1. Checked exception 예제
```
기존 예외 클래스는 Exception을 받아 반드시 강제적으로 예외 처리를 하도록 함.
때문에 예외처리가 불필요한 경우에도 try-catch문을 넣어 코드가 다소 복잡해짐.
(RuntimeException을 상속받지 않은 것은 다 Checked)
ex.IOException, SQLException

FileService.java
라인 63 uplopadFile 메소드

라인 82, 95 
파일 업로드는 파일이 반드시 input 되어야 하므로 예외처리 또한 반드시 해줘야 한다.
따라서 "파일이 존재하지 않는다"는 에러 메시지 발생 하도록 처리
```

2. Unchecked exception 예제
```
따라서 요즘은 필요에 따라 선택적으로 예외처리 할 수 있도록 바뀌어가고 있음.
(RuntimeException을 상속받으면 Unchecked exception)
ex. NullPointerException, IllegalArgumentException, IndexOutOfBoundException etc.

GroupException extends RuntimeException

적용 부분 GroupController.java
라인 126 deleteGroup 메소드

```

3. Finally 예제
```
try catch와 상관 없이 항상 실행이 보장되어야 하는 로직은 
finally에서 처리

NotebookVersionService.java
라인 201
```

4. Try with resource 예제
```
try(...)에서 선언된 객체들에 대해서 try가 종료될 때 자동으로 자원을 반납(close)해주는 기능
예컨대 try에서 선언된 객체가 AutoCloseable을 구현하였다면 Java는 try구문이
종료될 때 객체의 close() 메소드를 호출한다.
만든 클래스가 try-with-resources으로 자원이 해제되길 원한다면 AutoCloseable을 implements해야 한다.

CheetahSSHClient.java
CheetahSSHClient implements AutoCloseable

AnsibleService.java
라인 80 getMasterJoin 메소 - close()를 명시적으로 호출되지 않았음

```

5. Re-throwing 예제
```
한 메소드에서 발생할 수 있는 예외가 여럿이면 몇 개는 try-catch문을 통해 메소드 내 자체 처리,
나머지는 선언부에서 처리하도록 나눌 수 있다.
try-catch 문을 사용해 예외를 처리하고, catch 문에서 필요한 작업 후 throw문을 통해 
다시 예외를 발생시킨다. 다시 발생한 예외는 메소드를 호출한 메소드에 전달외어 
호출한 try-catch 문에서 또다시 처리한다.

DistributedGpuJobService.java
라인 50 executeJob 메소드의
    라인 68 throw e;
    
    JobException과 KubernetesException 등 여러 에외 발생 가능하므로 나누어 처리

```
